StarSocial/StarSocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

"""
Don't forget to check whether this can work without the other accounts/ url
This is for some urls provided by auth app, like "accounts/profile"
Can be avoided by re-define Login or Logout redirection url to other pages
"""
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('accounts/', include("django.contrib.auth.urls")),
    path('loggedin/', views.LoggedInPage.as_view(), name='loggedin'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

StarSocial/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='delete'),
]

StarSocial/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model

import misaka
from groups.models import Group
# Create your models here.
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name="posts", on_delete=models.CASCADE)
    created_time = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name="posts", null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("posts:single", kwargs={'username':self.user.username,
                                               'pk':self.pk})
    class Meta:
        ordering = ['-created_time']
        unique_together = ['user', 'message']

StarSocial/posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView
from django.http import Http404
from braces.views import SelectRelatedMixin
from django.contrib import messages
from .models import Post
from groups.models import Group
from . import forms
from django.contrib.auth import get_user_model
# Create your views here.

User = get_user_model()

class PostList(SelectRelatedMixin, ListView):
    model = Post
    template_name = 'posts/post_list.html'
    select_related = ('user', 'group')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_groups'] = Group.objects.filter(members__in=[self.request.user.pk])
        context['all_groups'] = Group.objects.all()
        return context

class UserPosts(ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            # Let's try a different way to achieve this goal
            self.post_user = User.objects.prefetch_related('posts').get(
                username__iexact=self.kwargs.get('username')
            )
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(DetailView, SelectRelatedMixin):
    model = Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, CreateView):
    fields = ('message', 'group')
    model = Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, DeleteView):
    model = Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        query_set = super().get_queryset()
        return query_set.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

StarSocial/posts/templates/posts/_post.html
<div class="media">
  <h3 style="margin-right:100px"><a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a></h3>

  <div class="media-body" style="margin-bottom:20px">
    <h5>{{post.message_html|safe}}</h5>
      <time class="time">
        <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{post.created_time}}</a>
      </time>
      {% if post.group %}
			<span class="group-name">in <a href="{% url 'groups:single' slug=post.group.slug %}">{{ post.group.name }}</a></span>
			{% endif %}
  </div>
  <div class="media-footer">
    {% if user.is_authenticated and post.user == user %}
      <a title="delete" href="{% url 'posts:delete' pk=post.pk %}" class="btn btn-simple">
        <span class="far fa-times-circle text-danger" aria-hidden="true">Delete</span>
      </a>
    {% endif %}
  </div>
</div>

StarSocial/posts/templates/posts/post_base.html
{% extends "base.html" %}

{% block content %}

<div class="posts-page">
  <div class="container">
    <div class="row">
      {% block prepost %}{% endblock %}
      {% block post_content %}{% endblock %}
      {% block postpost %}{% endblock %}
    </div>
  </div>
</div>

{% endblock %}

StarSocial/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}

<div class="container">
  <h3>Are you sure you want to delete this post?</h3>
  <div class="posts">
    {% include "posts/_post.html" with post=object hide_delete=True %}
  </div>

  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger btn-lg">
    <a href="{% url 'posts:single' username=user.username pk=object.pk %}"
      class="btn btn-light btn-lg">Cancel</a>
  </form>

</div>

{% endblock %}

StarSocial/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}

<div class="col-md-8">
  {% include "posts/_post.html" %}
</div>

{% endblock %}

StarSocial/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}
{% load bootstrap4 %}

{% block content %}

<h3>Create a new Post!</h3>
<form id="postForm" action="{% url 'posts:create' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" value="Post" class="btn btn-primary btn-lg">
</form>

{% endblock %}

StarSocial/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
  <!-- Try user.is_authenticated directly -->
  {% if user.is_authenticated %}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class="title" style="color:black">Your Groups</h5>
      <ul class="list-unstyled">
        {% for member_group in user_groups %}
          <li class="group li-with-bullet">
            <a href="{% url 'groups:single' slug=member_group.slug %}">{{member_group.name}}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  {% endif %}
  <div class="card card-with-shadow">
    <div class="content">
      <h5 class="title" style="color:black">All Groups</h5>
      <ul class="list-unstyled">
        {% for other_group in all_groups %}
        <li class="group li-with-bullet">
          <a href="{% url 'groups:single' slug=other_group.slug %}">{{other_group.name}}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </div>
</div>

{% endblock %}

{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
    {% include "posts/_post.html" %}
  {% endfor %}

</div>
{% endblock %}

StarSocial/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
<div class="col-md-4">
  <h1>@{{post_user.username}}</h1>
  <p>Post History</p>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
  {% for post in post_list %}
    {% include "posts/_post.html" %}
  {% endfor %}
</div>
{% endblock %}