StarSocial/StarSocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

"""
Don't forget to check whether this can work without the other accounts/ url
This is for some urls provided by auth app, like "accounts/profile"
Can be avoided by re-define Login or Logout redirection url to other pages
"""
urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('accounts/', include("django.contrib.auth.urls")),
    path('loggedin/', views.LoggedInPage.as_view(), name='loggedin'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('groups/', include('groups.urls', namespace='groups')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

StarSocial/groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name="all"),
    path('new/', views.CreateGroup.as_view(), name="create"),
    path('posts/in/<slug>', views.SingleGroup.as_view(), name="single"),
    path('join/<slug>', views.JoinGroup.as_view(), name="join"),
    path('leave/<slug>', views.LeaveGroup.as_view(), name="leave"),
]

StarSocial/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='delete'),
]

StarSocial/groups/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth import get_user_model
from django import template
from django.urls import reverse
import misaka

# Create your models here.
User = get_user_model()
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name="memberships", on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name="user_groups", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        # This field is to make sure that the same GroupMember can't be created
        # twice. Same, means both 'group' and 'user' are the same
        unique_together = ('group', 'user')

StarSocial/groups/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView, RedirectView
from .models import Group, GroupMember
from django.shortcuts import get_object_or_404

# Create your views here.

class CreateGroup(LoginRequiredMixin, CreateView):
    model = Group
    fields = ('name', 'description')

class SingleGroup(DetailView):
    model = Group

class ListGroups(ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except:
            messages.warning(self.request, ('Warning, already a member!'))
        else:
            messages.success(self.request, ('You are now a member!'))
        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except:
            messages.warning(self.request, ("Warning, you aren't in this group!"))
        else:
            membership.delete()
            messages.success(self.request, ('You have left the group!'))
        return super().get(request, *args, **kwargs)

StarSocial/groups/templates/groups/group_base.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>
{% endblock %}

StarSocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="container">
  <h1>{{ group.name }}</h1>
  <h2>Member Number: {{ group.members.count }}</h2>

  <div class="content">
    {% if user in group.members.all %}
      <a href="{% url 'groups:leave' slug=group.slug %}"
         class="btn btn-lg btn-warning">
         <span class="far fa-times-circle">Leave</span>
      </a>
    {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}"
       class="btn btn-lg btn-warning">
       <span class="far fa-check-circle">Join</span>
    </a>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
  {% if group.posts.count == 0 %}
    <h2>No post in this group yet!</h2>
  {% else %}
    {% for post in group.posts.all %}
    <!-- A way for inserting an html file inside an html file -->
      {% include "posts/_post.html" %}
    {% endfor %}
  {% endif %}

</div>
{% endblock %}

StarSocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap4 %}

{% block group_content %}
<div class="container">
  <h4>Create a new group!</h4>
  <form action="{% url 'groups:create' %}" method="post" id="group_form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-lg" value="Create">
  </form>
</div>
{% endblock %}

StarSocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}
{% block pregroup %}
  <div class="col-md-4">
    <div class="content">
      {% if user.is_authenticated %}
        <h2>Welcome Back!
          <a href="{% url 'posts:for_user' username=user.username%}">
            @{{ user.username }}
          </a>
        </h2>
      {% endif %}
      <h2>Groups</h2>
      <p>Welcome to the Groups Page! <br>Select a Group with a shared interest!</p>
    </div>
    {% if user.is_authenticated %}
      <a href="{% url 'groups:create' %}" class="btn btn-warning"><span class="fas fa-plus">Create New Group!</span></a>
    {% endif %}
  </div>
{% endblock %}

{% block group_content %}
  <div class="col-md-8">
    <div class="list-group">
      {% for group in object_list %}
        <a href="{% url 'groups:single' slug=group.slug %}"
    		   class="list-group-item list-group-item-action flex-column align-items-start">
    		  <h3 class="mb-1">{{ group.name }}</h3>
    			<p class="mb-1">{{ group.description_html|safe }}</p>
    			<div class="d-flex w-40 justify-content-between">
    				<small class="text-muted"><span class="badge badge-secondary">
    					{{ group.members.count }}</span> member{{ group.members.count|pluralize }}</small>
    				<small class="text-muted"><span class="badge badge-secondary">
    					{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}</small>
    			<span></span><span></span>
    			</div>
    		</a>
      {% endfor %}
    </div>
  </div>
{% endblock %}